apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3-gen3-testv2
  namespace: argocd
spec:
  project: default
  sources:
    - path: helm/gen3
      repoURL: https://github.com/uc-cdis/gen3-helm
      targetRevision: master
      helm:
        releaseName: gen3
        valueFiles:
          - $values/gen3-testv2/test.planx-pla.net/values/values.yaml
    - repoURL: '<git repo url>'
      targetRevision: master
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true